import test from "node:test";
import assert from "node:assert/strict";
import { deterministicTags, feasibilityDecision, jaccard, releaseDecade, stratifiedSample, usefulnessScore } from "../lib/analysis.ts";

test("release decade accepts partial Spotify dates",()=>{assert.equal(releaseDecade("1997-03-14"),"1990s");assert.equal(releaseDecade("2001"),"2000s");assert.equal(releaseDecade(null),null);});
test("deterministic tags retain provenance and conservative soundtrack confidence",()=>{const tags=deterministicTags({id:"t1",name:"Theme",albumName:"Original Motion Picture Soundtrack",artists:["A"],releaseDate:"2014",saved:true,playlistCount:1});assert.ok(tags.some(tag=>tag.dimension==="artist"&&tag.confidence==="high"));assert.ok(tags.some(tag=>tag.dimension==="decade"&&tag.value==="2010s"));assert.ok(tags.some(tag=>tag.dimension==="soundtrack"&&tag.confidence==="medium"));});
test("jaccard handles overlap and empty sets",()=>{assert.equal(jaccard([],[]),0);assert.equal(jaccard(["a","b"],["b","c"]),1/3);});
test("stratified sample is deterministic and bounded",()=>{const rows=Array.from({length:180},(_,index)=>({id:`t${index}`,releaseDate:`${1950+index%70}`,playlistCount:index%5}));const first=stratifiedSample(rows,100);assert.equal(first.length,100);assert.deepEqual(first,stratifiedSample(rows,100));assert.equal(new Set(first.map(row=>row.id)).size,100);});
test("usefulness uses the documented weighted score",()=>{assert.equal(usefulnessScore({coverage:80,cohesion:90,confidence:100,novelty:40}),83);});
test("feasibility is fail-closed on safety and policy",()=>{assert.equal(feasibilityDecision({normalizationRate:100,usefulSuggestions:3,precisionPass:true,writeVerified:true,policyCompatible:true}),"GO");assert.equal(feasibilityDecision({normalizationRate:100,usefulSuggestions:1,precisionPass:true,writeVerified:true,policyCompatible:true}),"REDUCE");assert.equal(feasibilityDecision({normalizationRate:100,usefulSuggestions:3,precisionPass:true,writeVerified:true,policyCompatible:false}),"STOP");});
