import { deterministicTags, jaccard, stratifiedSample, usefulnessScore, type TrackForAnalysis } from "@/lib/analysis";
import { getD1, nowIso, uid } from "@/lib/db";
import { getViewer } from "@/lib/identity";
import { apiError, json, routeError } from "@/lib/http";
import { enrichFromMusicBrainz } from "@/lib/musicbrainz";

type Run={id:string;user_id:string;status:string;phase:string;cursor_json:string;metrics_json:string};
type TrackRow={spotify_id:string;name:string;album_name:string|null;artist_names_json:string;release_date:string|null;saved:number;isrc:string|null;playlist_count:number};
type Candidate={rule:string;title:string;rationale:string;ids:string[];coverage:number;cohesion:number;confidence:number;novelty:number;usefulness:number};

async function loadTracks(userId:string){
  const rows=await getD1().prepare(`SELECT t.spotify_id,t.name,t.album_name,t.artist_names_json,t.release_date,t.saved,t.isrc,COUNT(DISTINCT pi.playlist_id) AS playlist_count FROM tracks t LEFT JOIN playlist_items pi ON pi.user_id=t.user_id AND pi.track_id=t.spotify_id WHERE t.user_id=? GROUP BY t.spotify_id ORDER BY t.spotify_id`).bind(userId).all<TrackRow>();
  return rows.results??[];
}

async function buildCandidates(db:D1Database,userId:string,totalTracks:number):Promise<{candidates:Candidate[];hygiene:Record<string,unknown>}>{
  const candidates:Candidate[]=[];
  const groups=await db.prepare(`SELECT dimension,value,COUNT(DISTINCT track_id) AS track_count,ROUND(AVG(score)) AS confidence FROM track_tags WHERE user_id=? AND confidence IN ('high','medium') GROUP BY dimension,value HAVING COUNT(DISTINCT track_id)>=5 ORDER BY track_count DESC LIMIT 30`).bind(userId).all<{dimension:string;value:string;track_count:number;confidence:number}>();
  for(const group of groups.results??[]){
    const ids=await db.prepare("SELECT track_id FROM track_tags WHERE user_id=? AND dimension=? AND value=? ORDER BY track_id").bind(userId,group.dimension,group.value).all<{track_id:string}>();
    const coverage=Math.min(100,Math.round(group.track_count/Math.max(1,totalTracks)*100));const cohesion=Math.min(100,65+Math.round(group.confidence*.3));const novelty=Math.max(35,100-coverage);
    candidates.push({rule:`${group.dimension}:${group.value}`,title:`${group.value} · ${group.dimension}`,rationale:`${group.track_count} tracks share a ${group.dimension} signal with ${group.confidence}% average confidence.`,ids:(ids.results??[]).map(row=>row.track_id),coverage,cohesion,confidence:group.confidence,novelty,usefulness:usefulnessScore({coverage,cohesion,confidence:group.confidence,novelty})});
  }
  const unfiled=await db.prepare(`SELECT spotify_id FROM tracks t WHERE t.user_id=? AND t.saved=1 AND NOT EXISTS (SELECT 1 FROM playlist_items pi WHERE pi.user_id=t.user_id AND pi.track_id=t.spotify_id) ORDER BY spotify_id`).bind(userId).all<{spotify_id:string}>();
  const unfiledIds=(unfiled.results??[]).map(row=>row.spotify_id);if(unfiledIds.length>=5){const coverage=Math.round(unfiledIds.length/Math.max(1,totalTracks)*100);candidates.push({rule:"hygiene:unfiled",title:"Unfiled saved tracks",rationale:`${unfiledIds.length} saved tracks do not appear in any imported playlist.`,ids:unfiledIds,coverage,cohesion:75,confidence:100,novelty:90,usefulness:usefulnessScore({coverage,cohesion:75,confidence:100,novelty:90})});}
  const duplicateRows=await db.prepare(`SELECT track_id,SUM(extra) AS extra FROM (SELECT track_id,COUNT(*)-1 AS extra FROM playlist_items WHERE user_id=? AND track_id IS NOT NULL GROUP BY playlist_id,track_id HAVING COUNT(*)>1) GROUP BY track_id`).bind(userId).all<{track_id:string;extra:number}>();
  const duplicateIds=(duplicateRows.results??[]).map(row=>row.track_id);if(duplicateIds.length>=5){const coverage=Math.round(duplicateIds.length/Math.max(1,totalTracks)*100);candidates.push({rule:"hygiene:duplicates",title:"Duplicate playlist entries",rationale:`${duplicateIds.length} tracks have repeated entries inside at least one playlist. This creates a review playlist only; it does not remove anything.`,ids:duplicateIds,coverage,cohesion:82,confidence:100,novelty:80,usefulness:usefulnessScore({coverage,cohesion:82,confidence:100,novelty:80})});}
  const crossRows=await db.prepare(`SELECT track_id,COUNT(DISTINCT playlist_id) AS playlist_count FROM playlist_items WHERE user_id=? AND track_id IS NOT NULL GROUP BY track_id HAVING COUNT(DISTINCT playlist_id)>=3 ORDER BY playlist_count DESC`).bind(userId).all<{track_id:string;playlist_count:number}>();
  const crossIds=(crossRows.results??[]).map(row=>row.track_id);if(crossIds.length>=5){const coverage=Math.round(crossIds.length/Math.max(1,totalTracks)*100);candidates.push({rule:"hygiene:cross-playlist",title:"Frequently repeated across playlists",rationale:`${crossIds.length} tracks occur in at least three playlists and may reveal overlapping organization.`,ids:crossIds,coverage,cohesion:70,confidence:100,novelty:68,usefulness:usefulnessScore({coverage,cohesion:70,confidence:100,novelty:68})});}
  const playlistRows=await db.prepare("SELECT playlist_id,track_id FROM playlist_items WHERE user_id=? AND track_id IS NOT NULL ORDER BY playlist_id").bind(userId).all<{playlist_id:string;track_id:string}>();
  const sets=new Map<string,Set<string>>();for(const row of playlistRows.results??[]){if(!sets.has(row.playlist_id))sets.set(row.playlist_id,new Set());sets.get(row.playlist_id)!.add(row.track_id);}const overlaps=[] as Array<{left:string;right:string;score:number}>;const playlistIds=[...sets.keys()];for(let left=0;left<playlistIds.length;left++)for(let right=left+1;right<playlistIds.length;right++){const score=jaccard(sets.get(playlistIds[left])!,sets.get(playlistIds[right])!);if(score>=.65)overlaps.push({left:playlistIds[left],right:playlistIds[right],score:Math.round(score*100)});}overlaps.sort((a,b)=>b.score-a.score);
  if(overlaps.length){const top=overlaps[0];const ids=[...new Set([...(sets.get(top.left)??[]),...(sets.get(top.right)??[])])];candidates.push({rule:`hygiene:overlap:${top.left}:${top.right}`,title:"Highly overlapping playlists",rationale:`Two playlists share ${top.score}% of their tracks. This review playlist contains their combined set.`,ids,coverage:Math.round(ids.length/Math.max(1,totalTracks)*100),cohesion:top.score,confidence:100,novelty:45,usefulness:usefulnessScore({coverage:Math.round(ids.length/Math.max(1,totalTracks)*100),cohesion:top.score,confidence:100,novelty:45})});}
  const subgroupRows=await db.prepare(`SELECT p.spotify_id,p.name,p.total_items,t.dimension,t.value,COUNT(DISTINCT pi.track_id) AS track_count,ROUND(AVG(t.score)) AS confidence FROM playlists p JOIN playlist_items pi ON pi.user_id=p.user_id AND pi.playlist_id=p.spotify_id JOIN track_tags t ON t.user_id=pi.user_id AND t.track_id=pi.track_id WHERE p.user_id=? AND p.total_items>=200 AND t.confidence IN ('high','medium') GROUP BY p.spotify_id,t.dimension,t.value HAVING COUNT(DISTINCT pi.track_id)>=20 AND COUNT(DISTINCT pi.track_id)*1.0/p.total_items>=0.2 ORDER BY track_count DESC LIMIT 10`).bind(userId).all<{spotify_id:string;name:string;total_items:number;dimension:string;value:string;track_count:number;confidence:number}>();
  for(const row of subgroupRows.results??[]){const ids=await db.prepare(`SELECT DISTINCT pi.track_id FROM playlist_items pi JOIN track_tags t ON t.user_id=pi.user_id AND t.track_id=pi.track_id WHERE pi.user_id=? AND pi.playlist_id=? AND t.dimension=? AND t.value=?`).bind(userId,row.spotify_id,row.dimension,row.value).all<{track_id:string}>();const coverage=Math.round(row.track_count/Math.max(1,totalTracks)*100);candidates.push({rule:`subgroup:${row.spotify_id}:${row.dimension}:${row.value}`,title:`${row.name} → ${row.value}`,rationale:`A coherent ${row.dimension} subgroup inside an oversized ${row.total_items}-track playlist.`,ids:(ids.results??[]).map(item=>item.track_id),coverage,cohesion:88,confidence:row.confidence,novelty:85,usefulness:usefulnessScore({coverage,cohesion:88,confidence:row.confidence,novelty:85})});}
  return {candidates,hygiene:{unfiled:unfiledIds.length,duplicateTracks:duplicateIds.length,crossPlaylistTracks:crossIds.length,highOverlapPairs:overlaps.length,oversizedSubgroups:(subgroupRows.results??[]).length}};
}

export async function POST(request:Request,context:{params:Promise<{id:string}>}){
  try{
    const viewer=getViewer(request);if(!viewer)return apiError("AUTH_REQUIRED","Sign in first.",401);const {id}=await context.params;const db=getD1();const run=await db.prepare("SELECT * FROM analysis_runs WHERE id=? AND user_id=?").bind(id,viewer.userId).first<Run>();if(!run)return apiError("NOT_FOUND","Analysis not found.",404);if(run.status==="complete")return json({run});const cursor=JSON.parse(run.cursor_json||"{}") as {sampleIds?:string[];externalIndex?:number};
    if(run.phase==="deterministic"){
      const rows=await loadTracks(viewer.userId);const tracks:TrackForAnalysis[]=rows.map(row=>({id:row.spotify_id,name:row.name,albumName:row.album_name,artists:JSON.parse(row.artist_names_json),releaseDate:row.release_date,saved:Boolean(row.saved),playlistCount:Number(row.playlist_count)}));
      const statements=tracks.flatMap(deterministicTags).map(tag=>db.prepare(`INSERT INTO track_tags (user_id,track_id,dimension,value,confidence,score,provenance,analysis_run_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(user_id,track_id,dimension,value) DO UPDATE SET confidence=excluded.confidence,score=excluded.score,provenance=excluded.provenance,analysis_run_id=excluded.analysis_run_id,updated_at=CURRENT_TIMESTAMP`).bind(viewer.userId,tag.trackId,tag.dimension,tag.value,tag.confidence,tag.score,tag.provenance,id));
      for(let start=0;start<statements.length;start+=90)await db.batch(statements.slice(start,start+90));const sampleIds=stratifiedSample(tracks,100).map(track=>track.id);const metrics={trackCount:tracks.length,sampleSize:sampleIds.length,normalizationRate:tracks.length?100:0,externalMatched:0,externalAttempted:0};await db.prepare("UPDATE analysis_runs SET phase='external',cursor_json=?,metrics_json=?,updated_at=? WHERE id=?").bind(JSON.stringify({sampleIds,externalIndex:0}),JSON.stringify(metrics),nowIso(),id).run();
    }else if(run.phase==="external"){
      const sampleIds=cursor.sampleIds??[];const externalIndex=cursor.externalIndex??0;if(externalIndex>=sampleIds.length)await db.prepare("UPDATE analysis_runs SET phase='suggestions',updated_at=? WHERE id=?").bind(nowIso(),id).run();else{const trackId=sampleIds[externalIndex];const track=await db.prepare("SELECT isrc FROM tracks WHERE user_id=? AND spotify_id=?").bind(viewer.userId,trackId).first<{isrc:string|null}>();let advance=true;const metrics=JSON.parse(run.metrics_json||"{}") as Record<string,number>;
        if(track?.isrc){const result=await enrichFromMusicBrainz(track.isrc);if(result.retryAfterMs)advance=false;else{metrics.externalAttempted=(metrics.externalAttempted??0)+1;if(result.matched){metrics.externalMatched=(metrics.externalMatched??0)+1;const tags:D1PreparedStatement[]=[];for(const genre of ((result.genres as string[]|undefined)??[]))tags.push(db.prepare(`INSERT INTO track_tags (user_id,track_id,dimension,value,confidence,score,provenance,analysis_run_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(user_id,track_id,dimension,value) DO UPDATE SET confidence=excluded.confidence,score=excluded.score,provenance=excluded.provenance,analysis_run_id=excluded.analysis_run_id,updated_at=CURRENT_TIMESTAMP`).bind(viewer.userId,trackId,"genre",genre,"medium",Math.min(95,Number(result.score??80)),"musicbrainz.isrc",id));if(result.soundtrack)tags.push(db.prepare(`INSERT INTO track_tags (user_id,track_id,dimension,value,confidence,score,provenance,analysis_run_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(user_id,track_id,dimension,value) DO UPDATE SET confidence=excluded.confidence,score=excluded.score,provenance=excluded.provenance,analysis_run_id=excluded.analysis_run_id,updated_at=CURRENT_TIMESTAMP`).bind(viewer.userId,trackId,"soundtrack","Soundtrack","high",95,"musicbrainz.isrc",id));if(tags.length)await db.batch(tags);}}}
        if(advance)await db.prepare("UPDATE analysis_runs SET cursor_json=?,metrics_json=?,updated_at=? WHERE id=?").bind(JSON.stringify({sampleIds,externalIndex:externalIndex+1}),JSON.stringify(metrics),nowIso(),id).run();}
    }else if(run.phase==="suggestions"){
      await db.prepare("DELETE FROM suggestions WHERE user_id=?").bind(viewer.userId).run();const total=await db.prepare("SELECT COUNT(*) AS count FROM tracks WHERE user_id=?").bind(viewer.userId).first<{count:number}>();const {candidates,hygiene}=await buildCandidates(db,viewer.userId,total?.count??0);candidates.sort((a,b)=>b.usefulness-a.usefulness);
      const statements=candidates.slice(0,20).map((candidate,rank)=>db.prepare(`INSERT INTO suggestions (id,user_id,analysis_run_id,rule,title,rationale,track_ids_json,track_count,coverage,cohesion,confidence,novelty,usefulness,rank,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(uid("sug"),viewer.userId,id,candidate.rule,candidate.title,candidate.rationale,JSON.stringify(candidate.ids),candidate.ids.length,candidate.coverage,candidate.cohesion,candidate.confidence,candidate.novelty,candidate.usefulness,rank+1));if(statements.length)await db.batch(statements);
      const metrics={...JSON.parse(run.metrics_json||"{}"),hygiene,suggestionCount:statements.length,usefulSuggestions:candidates.filter(candidate=>candidate.usefulness>=65).length};await db.prepare("UPDATE analysis_runs SET status='complete',phase='complete',metrics_json=?,completed_at=?,updated_at=? WHERE id=?").bind(JSON.stringify(metrics),nowIso(),nowIso(),id).run();
    }
    return json({run:await db.prepare("SELECT * FROM analysis_runs WHERE id=?").bind(id).first()});
  }catch(error){return routeError(error);}
}
