import { z } from "zod";import { sha256 } from "@/lib/crypto";import { getD1,nowIso,uid } from "@/lib/db";import { getViewer } from "@/lib/identity";import { apiError,json,parseJson,routeError } from "@/lib/http";import { spotifyFetch } from "@/lib/spotify";
const schema=z.object({idempotencyKey:z.string().min(8).max(120),snapshotHash:z.string().length(64)});
type Preview={id:string;user_id:string;suggestion_id:string;playlist_name:string;track_uris_json:string;snapshot_hash:string;status:string;expires_at:string};
type Operation={id:string;status:string;spotify_playlist_id:string|null};
export async function POST(request:Request,context:{params:Promise<{id:string}>}){try{const viewer=getViewer(request);if(!viewer)return apiError("AUTH_REQUIRED","Sign in first.",401);const {id}=await context.params;const body=await parseJson(request,schema);const db=getD1();const preview=await db.prepare("SELECT * FROM write_previews WHERE id=? AND user_id=?").bind(id,viewer.userId).first<Preview>();if(!preview)return apiError("NOT_FOUND","Write preview not found.",404);if(preview.snapshot_hash!==body.snapshotHash)return apiError("CONFLICT","The preview changed. Generate a new preview.",409);if(new Date(preview.expires_at).getTime()<Date.now())return apiError("CONFLICT","The preview expired. Generate a new one.",409);const uris=JSON.parse(preview.track_uris_json) as string[];const expectedHash=await sha256(JSON.stringify({suggestionId:preview.suggestion_id,uris,playlistName:preview.playlist_name}));if(expectedHash!==preview.snapshot_hash)return apiError("CONFLICT","The stored preview is stale.",409);
  let operation=await db.prepare("SELECT * FROM operations WHERE user_id=? AND idempotency_key=?").bind(viewer.userId,body.idempotencyKey).first<Operation>();if(!operation){const operationId=uid("op");await db.prepare("INSERT INTO operations (id,user_id,preview_id,idempotency_key,status) VALUES (?,?,?,?,'running')").bind(operationId,viewer.userId,id,body.idempotencyKey).run();operation={id:operationId,status:"running",spotify_playlist_id:null};}if(operation.status==="complete")return json({operation,alreadyCompleted:true});
  let playlistId=operation.spotify_playlist_id;if(!playlistId){const created=await spotifyFetch<{id:string}>(viewer.userId,"/me/playlists",{method:"POST",body:JSON.stringify({name:preview.playlist_name,public:false,collaborative:false,description:"Created by Sortify Phase 0 after an explicit preview and confirmation."})});playlistId=created.id;await db.prepare("UPDATE operations SET spotify_playlist_id=?,updated_at=? WHERE id=?").bind(playlistId,nowIso(),operation.id).run();}
  const batches=[] as string[][];for(let index=0;index<uris.length;index+=100)batches.push(uris.slice(index,index+100));for(let batchIndex=0;batchIndex<batches.length;batchIndex++){const existing=await db.prepare("SELECT status FROM operation_items WHERE operation_id=? AND batch_index=?").bind(operation.id,batchIndex).first<{status:string}>();if(existing?.status==="complete")continue;await db.prepare(`INSERT INTO operation_items (operation_id,batch_index,status,track_uris_json,created_at,updated_at) VALUES (?,?,'running',?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(operation_id,batch_index) DO UPDATE SET status='running',error=NULL,updated_at=CURRENT_TIMESTAMP`).bind(operation.id,batchIndex,JSON.stringify(batches[batchIndex])).run();try{const added=await spotifyFetch<{snapshot_id?:string}>(viewer.userId,`/playlists/${encodeURIComponent(playlistId)}/items`,{method:"POST",body:JSON.stringify({uris:batches[batchIndex]})});await db.prepare("UPDATE operation_items SET status='complete',snapshot_id=?,updated_at=? WHERE operation_id=? AND batch_index=?").bind(added.snapshot_id??null,nowIso(),operation.id,batchIndex).run();}catch(error){const message=error instanceof Error?error.message:String(error);await db.prepare("UPDATE operation_items SET status='failed',error=?,updated_at=? WHERE operation_id=? AND batch_index=?").bind(message,nowIso(),operation.id,batchIndex).run();await db.prepare("UPDATE operations SET status='failed',error=?,updated_at=? WHERE id=?").bind(message,nowIso(),operation.id).run();throw error;}}
  await db.batch([db.prepare("UPDATE operations SET status='complete',error=NULL,updated_at=? WHERE id=?").bind(nowIso(),operation.id),db.prepare("UPDATE write_previews SET status='confirmed',updated_at=? WHERE id=?").bind(nowIso(),id)]);return json({operation:{...operation,status:"complete",spotify_playlist_id:playlistId},playlistId,trackCount:uris.length});}catch(error){return routeError(error);}}
